name: 'dbt_snowflake_monitoring'
version: '5.2.1'
config-version: 2

profile: dbt_snowflake_monitoring

model-paths: ["models"]

clean-targets:
  - target
  - dbt_packages

models:
  # The config below applies only when running this package directly as a project, not when installed as a package in another project.
  +on_schema_change: "append_new_columns"
