name: 'dbt_snowflake_monitoring'
version: '4.0.2'
config-version: 2

profile: dbt_snowflake_monitoring

model-paths: ["models"]

clean-targets:
  - target
  - dbt_packages

models:
  +on_schema_change: "append_new_columns"
