version: 2

sources:
  - name: snowflake_account_usage
    database: snowflake
    schema: account_usage
    tables:
      - name: access_history
      - name: database_storage_usage_history
      - name: metering_daily_history
      - name: metering_history
      - name: query_history
      - name: serverless_task_history
      - name: stage_storage_usage_history
      - name: storage_usage
      - name: warehouse_events_history
      - name: warehouse_metering_history

  - name: snowflake_organization_usage
    database: snowflake
    schema: organization_usage
    tables:
      - name: rate_sheet_daily
      - name: remaining_balance_daily
      - name: usage_in_currency_daily

